import { MODEL_VERSION } from "./model.js";
import { radiansToDegrees } from "./geometry.js";

const escapeXml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));

export function buildSvg(solution, project, collision) {
  const flat = solution.flat; const all = [...flat.E, flat.O]; const minX = Math.min(...all.map((point) => point[0])); const maxX = Math.max(...all.map((point) => point[0])); const minY = Math.min(...all.map((point) => point[1])); const maxY = Math.max(...all.map((point) => point[1])); const padding = 12; const width = maxX - minX + padding * 2; const height = maxY - minY + padding * 2;
  const map = ([x, y]) => [x - minX + padding, maxY - y + padding]; const origin = map(flat.O); const endpoints = flat.E.map(map); const boundary = endpoints.map((point) => point.map((value) => value.toFixed(6)).join(",")).join(" ");
  const creaseLine = (point) => `<line x1="${origin[0].toFixed(6)}" y1="${origin[1].toFixed(6)}" x2="${point[0].toFixed(6)}" y2="${point[1].toFixed(6)}"/>`;
  const labels = endpoints.map((point, index) => `<text x="${(point[0] + 2).toFixed(6)}" y="${(point[1] - 2).toFixed(6)}">${index + 1}</text>`).join("");
  const mountain = solution.labels.map((label, index) => label === "mountain" ? creaseLine(endpoints[index]) : "").join(""); const valley = solution.labels.map((label, index) => label === "valley" ? creaseLine(endpoints[index]) : "").join(""); const flatLabels = solution.labels.every((label) => label === "flat") ? `<text x="${(origin[0] + 3).toFixed(6)}" y="${(origin[1] - 3).toFixed(6)}">all creases flat at q=0°</text>` : ""; const scaleX = width - padding - 10;
  return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${width.toFixed(6)}mm" height="${height.toFixed(6)}mm" viewBox="0 0 ${width.toFixed(6)} ${height.toFixed(6)}"><title>Foldline single-vertex Miura cell</title><metadata>format=${MODEL_VERSION}; alpha=${radiansToDegrees(project.alphaRad).toFixed(6)}deg; L=${project.Lmm.toFixed(6)}mm; branch=${project.branch}; q=${radiansToDegrees(project.qRad).toFixed(6)}deg; collision=${escapeXml(collision.status)}; model=zero-thickness rigid-hinge idealization</metadata><g id="boundary" fill="none" stroke="#1d2527" stroke-width="0.7"><polygon points="${boundary}"/></g><g id="mountain" fill="none" stroke="#bd594c" stroke-width="0.45" stroke-dasharray="2 1">${mountain}</g><g id="valley" fill="none" stroke="#3f7780" stroke-width="0.45" stroke-dasharray="2 1">${valley}</g><g id="labels" fill="#1d2527" font-family="sans-serif" font-size="3">${labels}<text x="${(origin[0] + 2).toFixed(6)}" y="${(origin[1] - 2).toFixed(6)}">O</text>${flatLabels}<text x="${padding}" y="${height - 3}">alpha ${radiansToDegrees(project.alphaRad).toFixed(3)}° / L ${project.Lmm.toFixed(1)} mm / branch ${project.branch > 0 ? "+1" : "−1"}</text><line x1="${scaleX.toFixed(6)}" y1="${(height - padding).toFixed(6)}" x2="${(scaleX + 10).toFixed(6)}" y2="${(height - padding).toFixed(6)}" stroke="#1d2527" stroke-width="0.7"/><text x="${scaleX.toFixed(6)}" y="${(height - padding - 2).toFixed(6)}">10 mm</text><text x="${padding}" y="${height - 9}">Score center creases; cut boundary only. Sampled collision check, not physical clearance.</text></g></svg>`;
}
